import math
import string

class TypoCoderDiv2:
  def count(self, rating):
    # rating = list(rating)
    # cur =500
    # change = 0
    # for i in xrange(len(rating)):
    #   change += ((rating[i] >= 1200) != (cur >= 1200))
    #   cur = rating[i]
    #
    # return change

    rating = list(rating)
    current = 2
    count = 0

    for r in rating:
      if r < 1200 and current == 1:
        count += 1
        current = 2
      if r >= 1200 and current == 2:
        count += 1
        current = 1

    return count

# BEGIN KAWIGIEDIT TESTING
# Generated by KawigiEdit-pfx 2.1.9
import sys
import time
def KawigiEdit_RunTest(testNum, p0, hasAnswer, p1):
	sys.stdout.write(str("Test ") + str(testNum) + str(": [") + str("{"))
	for i in range(len(p0)):
		if (i > 0):
			sys.stdout.write(str(","))
		
		sys.stdout.write(str(p0[i]))
	
	sys.stdout.write(str("}"))
	print(str("]"))
	obj = TypoCoderDiv2()
	startTime = time.clock()
	answer = obj.count(p0)
	endTime = time.clock()
	res = True
	print(str("Time: ") + str((endTime - startTime)) + str(" seconds"))
	if (hasAnswer):
		print(str("Desired answer:"))
		print(str("\t") + str(p1))
	
	print(str("Your answer:"))
	print(str("\t") + str(answer))
	if (hasAnswer):
		res = answer == p1
	
	if (not res):
		print(str("DOESN'T MATCH!!!!"))
	elif ((endTime - startTime) >= 2):
		print(str("FAIL the timeout"))
		res = False
	elif (hasAnswer):
		print(str("Match :-)"))
	else:
		print(str("OK, but is it right?"))
	
	print(str(""))
	return res

all_right = True


# ----- test 0 -----
p0 = [1000,1200,1199]
p1 = 2
all_right = KawigiEdit_RunTest(0, p0, True, p1) and all_right
# ------------------

# ----- test 1 -----
p0 = [1500,2200,900,3000]
p1 = 3
all_right = KawigiEdit_RunTest(1, p0, True, p1) and all_right
# ------------------

# ----- test 2 -----
p0 = [600,700,800,900,1000,1100,1199]
p1 = 0
all_right = KawigiEdit_RunTest(2, p0, True, p1) and all_right
# ------------------

# ----- test 3 -----
p0 = [0,4000,0,4000,4000,0,0]
p1 = 4
all_right = KawigiEdit_RunTest(3, p0, True, p1) and all_right
# ------------------

# ----- test 4 -----
p0 = [575,1090,3271,2496,859,2708,3774,2796,1616,2552,3783,2435,1111,526,562]
p1 = 4
all_right = KawigiEdit_RunTest(4, p0, True, p1) and all_right
# ------------------

if (all_right):
	print(str("You're a stud (at least on the example cases)!"))
else:
	print(str("Some of the test cases had errors."))

# PROBLEM STATEMENT
# TypoCoder is a programming contest like TopCoder.
# TypoCoder also has a rating system.
# There are two types of coders in TypoCoder: brown coders and ciel coders.
# A brown coder is a coder whose rating is greater than or equal to 1200.
# A ciel coder is a coder whose rating is less than 1200.
#
# Whenever a new contestant joins TypoCoder, their rating is 500.
# Cat Lower joined TypoCoder and then competed in some contests.
# You are given a tuple (integer) rating.
# For each i (0-based index), rating[i] is Cat Lower's rating after he competed in (i+1) contests.
#
# Return the number of times Cat Lower changed his color (i.e., changed from being a ciel coder to being a brown coder or back).
#
# DEFINITION
# Class:TypoCoderDiv2
# Method:count
# Parameters:tuple (integer)
# Returns:integer
# Method signature:def count(self, rating):
# 
# 
# CONSTRAINTS
# -rating will contain between 1 and 50 elements, inclusive.
# -Each element of rating will be between 0 and 4000, inclusive.
# 
# 
# EXAMPLES
# 
# 0)
# {1000,1200,1199}
# 
# Returns: 2
# 
# After the first contest Cat Lower was still a ciel coder. After the second contest his new rating was 1200 which made him a brown coder. (This was the first color change.) After the third contest his new rating was 1199 which made him a ciel coder again. (This was the second color change.)
# 
# 1)
# {1500,2200,900,3000}
# 
# Returns: 3
# 
# The color changed after the first, the third and the fourth competition.
# 
# 2)
# {600,700,800,900,1000,1100,1199}
# 
# Returns: 0
# 
# Cat Lower wasn't a brown coder at any time in this case.
# 
# 3)
# {0,4000,0,4000,4000,0,0}
# 
# Returns: 4
# 
# 
# 
# 4)
# {575,1090,3271,2496,859,2708,3774,2796,1616,2552,3783,2435,1111,526,562}
# 
# Returns: 4
# 
# 
# 
# END KAWIGIEDIT TESTING
#Powered by KawigiEdit-pfx 2.1.9!
