import math
import string

class TheShuttles:
    def getLeastCost(self, cnt, baseCost, seatCost):
        cnt = list(cnt)
        m = max(cnt)

        mini = 100000000000
        for i in xrange(1, m + 1):
            sum = 0
            for c in cnt:
                sum += (baseCost + (seatCost * i)) * math.ceil(float(c) / i)
            mini = min(mini, sum)

        return mini
        

# BEGIN KAWIGIEDIT TESTING
# Generated by KawigiEdit-pfx 2.1.9
import sys
import time
def KawigiEdit_RunTest(testNum, p0, p1, p2, hasAnswer, p3):
	sys.stdout.write(str("Test ") + str(testNum) + str(": [") + str("{"))
	for i in range(len(p0)):
		if (i > 0):
			sys.stdout.write(str(","))
		
		sys.stdout.write(str(p0[i]))
	
	sys.stdout.write(str("}") + str(",") + str(p1) + str(",") + str(p2))
	print(str("]"))
	obj = TheShuttles()
	startTime = time.clock()
	answer = obj.getLeastCost(p0, p1, p2)
	endTime = time.clock()
	res = True
	print(str("Time: ") + str((endTime - startTime)) + str(" seconds"))
	if (hasAnswer):
		print(str("Desired answer:"))
		print(str("\t") + str(p3))
	
	print(str("Your answer:"))
	print(str("\t") + str(answer))
	if (hasAnswer):
		res = answer == p3
	
	if (not res):
		print(str("DOESN'T MATCH!!!!"))
	elif ((endTime - startTime) >= 2):
		print(str("FAIL the timeout"))
		res = False
	elif (hasAnswer):
		print(str("Match :-)"))
	else:
		print(str("OK, but is it right?"))
	
	print(str(""))
	return res

all_right = True


# ----- test 0 -----
p0 = [9]
p1 = 30
p2 = 5
p3 = 75
all_right = KawigiEdit_RunTest(0, p0, p1, p2, True, p3) and all_right
# ------------------

# ----- test 1 -----
p0 = [9,4]
p1 = 30
p2 = 5
p3 = 150
all_right = KawigiEdit_RunTest(1, p0, p1, p2, True, p3) and all_right
# ------------------

# ----- test 2 -----
p0 = [9,4]
p1 = 10
p2 = 5
p3 = 105
all_right = KawigiEdit_RunTest(2, p0, p1, p2, True, p3) and all_right
# ------------------

# ----- test 3 -----
p0 = [51,1,77,14,17,10,80]
p1 = 32
p2 = 40
p3 = 12096
all_right = KawigiEdit_RunTest(3, p0, p1, p2, True, p3) and all_right
# ------------------

# ----- test 3 -----
p0 = [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
      100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
      100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
      100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
      100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
      100, 100, 100, 100, 100]
p1 = 100
p2 = 100
p3 = 12096
all_right = KawigiEdit_RunTest(3, p0, p1, p2, True, p3) and all_right
# ------------------


if (all_right):
	print(str("You're a stud (at least on the example cases)!"))
else:
	print(str("Some of the test cases had errors."))

# PROBLEM STATEMENT
# Note that the memory limit for all tasks in this SRM is 256 MB.
#
# The company Manao Inc. cares for its employees and tries to provide them with as much comfort as possible. One of the services Manao Inc. provides is transportation of employees from N distant locations to the office. The locations are numbered from 0 to N-1. You are given a tuple (integer) cnt containing N elements. The i-th (0-based index) element of cnt is the number of employees who live near location i.
#
# The company wants to purchase several shuttles of the same size. These shuttles will then be used for employee transportation. Each of the shuttles will only serve one particular location. Each location will be assigned the smallest number of shuttles sufficient to transport all of the employees living close to it.
#
# The cost of a shuttle consists of the cost baseCost of its frame and some additional cost seatCost per each seat. That is, a shuttle with X seats will cost baseCost + X * seatCost. For its shuttles, Manao Inc. can choose X to be any positive integer. (But remember that all the shuttles must have the same X.) Compute and return the least amount of money the company needs to spend on the shuttles in order to provide transportation for all employees.
#
# DEFINITION
# Class:TheShuttles
# Method:getLeastCost
# Parameters:tuple (integer), integer, integer
# Returns:integer
# Method signature:def getLeastCost(self, cnt, baseCost, seatCost):
# 
# 
# CONSTRAINTS
# -cnt will contain between 1 and 50 elements, inclusive.
# -Each element of cnt will be between 1 and 100, inclusive.
# -baseCost will be between 1 and 100, inclusive.
# -seatCost will be between 1 and 100, inclusive.
# 
# 
# EXAMPLES
# 
# 0)
# {9}
# 30
# 5
# 
# Returns: 75
# 
# Manao Inc. provides transportation for its employees from a single location. There are 9 employees living near it. A shuttle with X seats will cost the company 30 + 5X. It is optimal to buy a single shuttle with 9 seats.
# 
# 1)
# {9, 4}
# 30
# 5
# 
# Returns: 150
# 
# Manao Inc. provides transportation from two locations. There are 9 employees living near location 0 and 4 employees living near location 1. It is optimal to buy two shuttles with 9 seats each and send a single shuttle to each location. (Note that the shuttles we buy must all be of the same size. It is not allowed to buy one shuttle with 9 and another with 4 seats.)
# 
# 2)
# {9, 4}
# 10
# 5
# 
# Returns: 105
# 
# This is the same test as the previous example, but baseCost is lower. It is optimal to buy three shuttles with 5 seats each and send two shuttles to location 0 and one shuttle to location 1.
# 
# 3)
# {51, 1, 77, 14, 17, 10, 80}
# 32
# 40
# 
# Returns: 12096
# 
# 
# 
# END KAWIGIEDIT TESTING

#Powered by KawigiEdit-pfx 2.1.9!
