import math
import string

class EllysSubstringSorter:
  def getMin(self, S, L):
    # cee = sorted(list(S))
    # correct = ''.join(cee)
    #
    # max_n = 0
    ans = []

    for i in xrange(len(S) - L  + 1):
      s0 = list(S[0:i])
      s1 = list(S[i:L + i])
      s2 = list(S[L + i:])
      s1.sort()
      s = ''.join(s0 + s1 + s2)
      ans.append(s)

      ans.sort()

    return ans[0]

# BEGIN KAWIGIEDIT TESTING
# Generated by KawigiEdit-pfx 2.1.9
import sys
import time
def KawigiEdit_RunTest(testNum, p0, p1, hasAnswer, p2):
	sys.stdout.write(str("Test ") + str(testNum) + str(": [") + str("\"") + str(p0) + str("\"") + str(",") + str(p1))
	print(str("]"))
	obj = EllysSubstringSorter()
	startTime = time.clock()
	answer = obj.getMin(p0, p1)
	endTime = time.clock()
	res = True
	print(str("Time: ") + str((endTime - startTime)) + str(" seconds"))
	if (hasAnswer):
		print(str("Desired answer:"))
		print(str("\t") + str("\"") + str(p2) + str("\""))
	
	print(str("Your answer:"))
	print(str("\t") + str("\"") + str(answer) + str("\""))
	if (hasAnswer):
		res = answer == p2
	
	if (not res):
		print(str("DOESN'T MATCH!!!!"))
	elif ((endTime - startTime) >= 2):
		print(str("FAIL the timeout"))
		res = False
	elif (hasAnswer):
		print(str("Match :-)"))
	else:
		print(str("OK, but is it right?"))
	
	print(str(""))
	return res

all_right = True


# ----- test 0 -----
p0 = "TOPCODER"
p1 = 4
p2 = "COPTODER"
all_right = KawigiEdit_RunTest(0, p0, p1, True, p2) and all_right
# ------------------

# ----- test 1 -----
p0 = "ESPRIT"
p1 = 3
p2 = "EPRSIT"
all_right = KawigiEdit_RunTest(1, p0, p1, True, p2) and all_right
# ------------------

# ----- test 2 -----
p0 = "AAAAAAAAA"
p1 = 2
p2 = "AAAAAAAAA"
all_right = KawigiEdit_RunTest(2, p0, p1, True, p2) and all_right
# ------------------

# ----- test 3 -----
p0 = "ABRACADABRA"
p1 = 5
p2 = "AAABCRDABRA"
all_right = KawigiEdit_RunTest(3, p0, p1, True, p2) and all_right
# ------------------

# ----- test 4 -----
p0 = "BAZINGA"
p1 = 6
p2 = "ABGINZA"
all_right = KawigiEdit_RunTest(4, p0, p1, True, p2) and all_right
# ------------------

# ----- test 5 -----
p0 = "AAAWDIUAOIWDESBEAIWODJAWDBPOAWDUISAWDOOPAWD"
p1 = 21
p2 = "AAAAAABDDDEEIIIJOOSUWWWWDBPOAWDUISAWDOOPAWD"
all_right = KawigiEdit_RunTest(5, p0, p1, True, p2) and all_right
# ------------------

if (all_right):
	print(str("You're a stud (at least on the example cases)!"))
else:
	print(str("Some of the test cases had errors."))

# PROBLEM STATEMENT
# Elly has a string S of uppercase letters and a magic device that can modify the string. The strength of the device is an integer L.
#
# The device does the following: The user enters a 0-based index i such that 0 <= i <= length(S)-L. The device then takes L letters of S, starting at index i, and puts these letters into alphabetical order.
# Formally, the letters that get reordered are the letters S[i], S[i+1], and so on, until and including S[i+L-1].
#
# For example, let S="TOPCODER" and let L=4. If the user chooses i=0, the selected substring will be "TOPC". These letters are rearranged into alphabetical order ("COPT") while the rest of the string remains unchanged ("....ODER"). Thus, the result would be the string "COPTODER". If the user were to choose i=2 instead, the resulting string would be "TOCDOPER". Here, "TO....ER" was left unchanged, and "PCOD" was changed into "CDOP".
#
# Elly's magic device has a flaw: it can only be used once and then it self-destructs. You are given the string S and the integer L described above. Return the lexicographically smallest string Elly can create by using the device exactly once.
#
# 
# DEFINITION
# Class:EllysSubstringSorter
# Method:getMin
# Parameters:string, integer
# Returns:string
# Method signature:def getMin(self, S, L):
# 
# 
# NOTES
# -A string S1 is lexicographically smaller than a string S2 if S1 contains a smaller character than S2 at the first index where they differ.
# 
# 
# CONSTRAINTS
# -L will be between 2 and 50, inclusive.
# -S will contain between L and 50 characters, inclusive.
# -Each character of S will be an uppercase letter of the English alphabet ('A'-'Z').
# 
# 
# EXAMPLES
# 
# 0)
# "TOPCODER"
# 4
# 
# Returns: "COPTODER"
# 
# The best we can do here is to sort the first 4 characters of the string.
# 
# 1)
# "ESPRIT"
# 3
# 
# Returns: "EPRSIT"
# 
# The best solution is obtained by choosing i=1, i.e., by sorting the letters in the substring "SPR".
# 
# 2)
# "AAAAAAAAA"
# 2
# 
# Returns: "AAAAAAAAA"
# 
# Sometimes sorting doesn't do anything.
# 
# 3)
# "ABRACADABRA"
# 5
# 
# Returns: "AAABCRDABRA"
# 
# 
# 
# 4)
# "BAZINGA"
# 6
# 
# Returns: "ABGINZA"
# 
# 
# 
# 5)
# "AAAWDIUAOIWDESBEAIWODJAWDBPOAWDUISAWDOOPAWD"
# 21
# 
# Returns: "AAAAAABDDDEEIIIJOOSUWWWWDBPOAWDUISAWDOOPAWD"
# 
# 
# 
# END KAWIGIEDIT TESTING
#Powered by KawigiEdit-pfx 2.1.9!
