import math
import string

class EllysNumberGuessing:
  def getNumber(self, guesses, answers):
    candi = []
    if 0 < guesses[0] + answers[0] <= 1000000000:
      candi.append(guesses[0] + answers[0])
    if 0 < guesses[0] - answers[0] <= 1000000000:
      candi.append(guesses[0] - answers[0])
    # print candi

    for g, a in zip(guesses, answers):
      pp = g + a
      mm = g - a

      for i in range(len(candi)):
        if candi[i] != pp and candi[i] != mm:
          candi[i] = -1

      candi = [c for c in candi if c > -1]
    print candi
    l =  len(candi)

    if l == 2:
      return -1
    if l == 0:
      return -2
    return candi[0]



# BEGIN KAWIGIEDIT TESTING
# Generated by KawigiEdit-pfx 2.1.9
import sys
import time
def KawigiEdit_RunTest(testNum, p0, p1, hasAnswer, p2):
	sys.stdout.write(str("Test ") + str(testNum) + str(": [") + str("{"))
	for i in range(len(p0)):
		if (i > 0):
			sys.stdout.write(str(","))
		
		sys.stdout.write(str(p0[i]))
	
	sys.stdout.write(str("}") + str(",") + str("{"))
	for i in range(len(p1)):
		if (i > 0):
			sys.stdout.write(str(","))
		
		sys.stdout.write(str(p1[i]))
	
	sys.stdout.write(str("}"))
	print(str("]"))
	obj = EllysNumberGuessing()
	startTime = time.clock()
	answer = obj.getNumber(p0, p1)
	endTime = time.clock()
	res = True
	print(str("Time: ") + str((endTime - startTime)) + str(" seconds"))
	if (hasAnswer):
		print(str("Desired answer:"))
		print(str("\t") + str(p2))
	
	print(str("Your answer:"))
	print(str("\t") + str(answer))
	if (hasAnswer):
		res = answer == p2
	
	if (not res):
		print(str("DOESN'T MATCH!!!!"))
	elif ((endTime - startTime) >= 2):
		print(str("FAIL the timeout"))
		res = False
	elif (hasAnswer):
		print(str("Match :-)"))
	else:
		print(str("OK, but is it right?"))
	
	print(str(""))
	return res

all_right = True


# ----- test 0 -----
p0 = [600,594]
p1 = [6,12]
p2 = 606
all_right = KawigiEdit_RunTest(0, p0, p1, True, p2) and all_right
# ------------------

# ----- test 1 -----
p0 = [100,50,34,40]
p1 = [58,8,8,2]
p2 = 42
all_right = KawigiEdit_RunTest(1, p0, p1, True, p2) and all_right
# ------------------

# ----- test 2 -----
p0 = [500000,600000,700000]
p1 = [120013,220013,79987]
p2 = -2
all_right = KawigiEdit_RunTest(2, p0, p1, True, p2) and all_right
# ------------------

# ----- test 3 -----
p0 = [500000000]
p1 = [133742666]
p2 = -1
all_right = KawigiEdit_RunTest(3, p0, p1, True, p2) and all_right
# ------------------

# ----- test 4 -----
p0 = [76938260,523164588,14196746,296286419,535893832,41243148,364561227,270003278,472017422,367932361,395758413,301278456,186276934,316343129,336557549,52536121,98343562,356769915,89249181,335191879]
p1 = [466274085,20047757,529015599,246925926,7318513,501969197,178651118,273209067,71194923,175279984,147453932,241933889,356935411,226869216,206654796,490676224,444868783,186442430,453963164,208020466]
p2 = 543212345
all_right = KawigiEdit_RunTest(4, p0, p1, True, p2) and all_right
# ------------------

# ----- test 5 -----
p0 = [42]
p1 = [42]
p2 = 84
all_right = KawigiEdit_RunTest(5, p0, p1, True, p2) and all_right
# ------------------

# ----- test 6 -----
p0 = [999900000]
p1 = [100001]
p2 = 999799999
all_right = KawigiEdit_RunTest(6, p0, p1, True, p2) and all_right
# ------------------


# ----- test 6 -----
p0 = [2]
p1 = [999999999]
p2 = -2
all_right = KawigiEdit_RunTest(6, p0, p1, True, p2) and all_right
# ------------------

if (all_right):
	print(str("You're a stud (at least on the example cases)!"))
else:
	print(str("Some of the test cases had errors."))

# PROBLEM STATEMENT
# Elly and Kris play the following game. In the beginning Kristina thinks of a number between 1 and 1,000,000,000, inclusive. After that Elly starts trying to guess it. In each round she says a number and Kristina says what is the absolute difference between the number she has thought of, and the number Elly guessed. Now Elly wonders if the guesses she has already made are sufficient to uniquely determine Kristina's number.
#
# You are given a tuple (integer) guesses and a tuple (integer) answers of the same length. For each valid i, in round i of the game (0-based index) Elly guessed the number guesses[i] and Kristina answered answers[i]. If Kristina's number can be uniquely determined, return that number. If there are multiple possibilities that are consistent with the current set of guesses and answers, return -1. If it can be shown that at some point Kristina has lied (some of her answers were inconsistent), return -2.
#
# DEFINITION
# Class:EllysNumberGuessing
# Method:getNumber
# Parameters:tuple (integer), tuple (integer)
# Returns:integer
# Method signature:def getNumber(self, guesses, answers):
#
#
# CONSTRAINTS
# -guesses and answers will each contain between 1 and 50 elements, inclusive.
# -guesses and answers will contain the same number of elements.
# -Each element of guesses will be between 1 and 1,000,000,000, inclusive.
# -Each element of answers will be between 1 and 999,999,999, inclusive.
# 
# 
# EXAMPLES
# 
# 0)
# {600, 594}
# {6, 12}
# 
# Returns: 606
# 
# Apparently Kristina has thought of the number of this SRM.
# 
# 1)
# {100, 50, 34, 40}
# {58, 8, 8, 2}
# 
# Returns: 42
# 
# It is not guaranteed that Elly has used a perfect strategy so far.
# 
# 2)
# {500000, 600000, 700000}
# {120013, 220013, 79987}
# 
# Returns: -2
# 
# The answers here are inconsistent. After the second guess we can conclude that the answer is below 500000. But the third one indicates that it is above 500000. Thus, Kristina is a liar and you should return -2.
# 
# 3)
# {500000000}
# {133742666}
# 
# Returns: -1
# 
# There are multiple possibilities here, thus you should return -1.
# 
# 4)
# {76938260, 523164588, 14196746, 296286419, 535893832,
#  41243148, 364561227, 270003278, 472017422, 367932361,
#  395758413, 301278456, 186276934, 316343129, 336557549,
#  52536121, 98343562, 356769915, 89249181, 335191879}
# {466274085, 20047757, 529015599, 246925926, 7318513,
#  501969197, 178651118, 273209067, 71194923, 175279984,
#  147453932, 241933889, 356935411, 226869216, 206654796,
#  490676224, 444868783, 186442430, 453963164, 208020466}
# 
# Returns: 543212345
# 
# 
# 
# 5)
# {42}
# {42}
# 
# Returns: 84
# 
# Don't forget that the number Kris has thought of must be between 1 and 1,000,000,000.
# 
# 6)
# {999900000}
# {100001}
# 
# Returns: 999799999
# 
# Don't forget that the number Kris has thought of must be between 1 and 1,000,000,000.
# 
# END KAWIGIEDIT TESTING
#Powered by KawigiEdit-pfx 2.1.9!
