import math
import string

class LittleElephantAndBallsAgain:
    def getNumber(self, S):
        c = S[0]
        longest = 0
        l = 1
        for s in S[1::]:
            if s != c:
                longest = max(longest, l)
                l = 1
                c = s
            else:
                l += 1
        longest = max(longest, l)
        return len(S) - longest

# BEGIN KAWIGIEDIT TESTING
# Generated by KawigiEdit-pfx 2.1.9
import sys
import time
def KawigiEdit_RunTest(testNum, p0, hasAnswer, p1):
	sys.stdout.write(str("Test ") + str(testNum) + str(": [") + str("\"") + str(p0) + str("\""))
	print(str("]"))
	obj = LittleElephantAndBallsAgain()
	startTime = time.clock()
	answer = obj.getNumber(p0)
	endTime = time.clock()
	res = True
	print(str("Time: ") + str((endTime - startTime)) + str(" seconds"))
	if (hasAnswer):
		print(str("Desired answer:"))
		print(str("\t") + str(p1))
	
	print(str("Your answer:"))
	print(str("\t") + str(answer))
	if (hasAnswer):
		res = answer == p1
	
	if (not res):
		print(str("DOESN'T MATCH!!!!"))
	elif ((endTime - startTime) >= 2):
		print(str("FAIL the timeout"))
		res = False
	elif (hasAnswer):
		print(str("Match :-)"))
	else:
		print(str("OK, but is it right?"))
	
	print(str(""))
	return res

all_right = True


# ----- test 0 -----
p0 = "RRGGBB"
p1 = 4
all_right = KawigiEdit_RunTest(0, p0, True, p1) and all_right
# ------------------

# ----- test 1 -----
p0 = "R"
p1 = 0
all_right = KawigiEdit_RunTest(1, p0, True, p1) and all_right
# ------------------

# ----- test 2 -----
p0 = "RGBRGB"
p1 = 5
all_right = KawigiEdit_RunTest(2, p0, True, p1) and all_right
# ------------------

# ----- test 3 -----
p0 = "RGGGBB"
p1 = 3
all_right = KawigiEdit_RunTest(3, p0, True, p1) and all_right
# ------------------

# ----- test 4 -----
p0 = "RGBRBRGRGRBBBGRBRBRGBGBBBGRGBBBBRGBGRRGGRRRGRBBBBR"
p1 = 46
all_right = KawigiEdit_RunTest(4, p0, True, p1) and all_right
# ------------------

# ----- test 5 -----
p0 = "RRRRR"
p1 = 0
all_right = KawigiEdit_RunTest(5, p0, True, p1) and all_right
# ------------------

# ----- test 6 -----
p0 = "AAA"
p1 = 1
all_right = KawigiEdit_RunTest(6, p0, True, p1) and all_right
# ------------------

# ----- test 7 -----
p0 = "11"
p1 = 111
all_right = KawigiEdit_RunTest(7, p0, True, p1) and all_right
# ------------------

if (all_right):
	print(str("You're a stud (at least on the example cases)!"))
else:
	print(str("Some of the test cases had errors."))

# PROBLEM STATEMENT
# 
# Little Elephant from the Zoo of Lviv likes balls. He has some balls arranged in a row. Each of those balls has one of three possible colors: red, green, or blue.
# 
# 
# 
# 
# You are given a string S. This string represents all the balls that are initially in the row (in the order from left to right). Red, green, and blue balls are represented by characters 'R', 'G', and 'B', respectively. In one turn Little Elephant can remove either the first ball in the row, or the last one. 
# 
# 
# 
# 
# Little Elephant wants to obtain a row in which all balls have the same color.
# Return the smallest number of turns in which this can be done.
# 
# 
# DEFINITION
# Class:LittleElephantAndBallsAgain
# Method:getNumber
# Parameters:string
# Returns:integer
# Method signature:def getNumber(self, S):
# 
# 
# CONSTRAINTS
# -S will contain between 1 and 50 characters, inclusive.
# -S will consist only of characters 'R', 'G' and 'B'.
# 
# 
# EXAMPLES
# 
# 0)
# "RRGGBB"
# 
# Returns: 4
# 
# One possible optimal solution is to remove 2 balls from the front and 2 from the back. The total number of turns is 2+2 = 4. After those 4 turns only green balls remained on the table.
# 
# 1)
# "R"
# 
# Returns: 0
# 
# You don't need to do any turns in this case, so the answer is 0.
# 
# 2)
# "RGBRGB"
# 
# Returns: 5
# 
# In any optimal solution only one of these six balls will remain on the table.
# 
# 3)
# "RGGGBB"
# 
# Returns: 3
# 
# 
# 
# 4)
# "RGBRBRGRGRBBBGRBRBRGBGBBBGRGBBBBRGBGRRGGRRRGRBBBBR"
# 
# Returns: 46
# 
# 
# 
# END KAWIGIEDIT TESTING
#Powered by KawigiEdit-pfx 2.1.9!
